<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-DT297E4" failures="4" tests="10" name="Test" time="161.011" errors="0" timestamp="2022-08-29T19:22:46 IST">
  <testcase classname="testCases.TC_001_AccountRegistrationTest" name="test_account_Registration" time="7.348"/>
  <testcase classname="testCases.TC_002_LoginTest" name="test_login" time="1.931"/>
  <testcase classname="testCases.TC_003_LoginDataDrivenTest" name="test_Loginddt" time="14.717">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_003_LoginDataDrivenTest.test_Loginddt(TC_003_LoginDataDrivenTest.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_Loginddt -->
  <testcase classname="testCases.TC_003_LoginDataDrivenTest" name="test_Loginddt" time="12.916">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_003_LoginDataDrivenTest.test_Loginddt(TC_003_LoginDataDrivenTest.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_Loginddt -->
  <testcase classname="testCases.TC_003_LoginDataDrivenTest" name="test_Loginddt" time="11.363">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_003_LoginDataDrivenTest.test_Loginddt(TC_003_LoginDataDrivenTest.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_Loginddt -->
  <testcase classname="testCases.TC_003_LoginDataDrivenTest" name="test_Loginddt" time="12.063">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_003_LoginDataDrivenTest.test_Loginddt(TC_003_LoginDataDrivenTest.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_Loginddt -->
  <testcase classname="testCases.TC_003_LoginDataDrivenTest" name="test_Loginddt" time="2.279"/>
  <testcase classname="testCases.TC_004_SearchProductTest" name="test_productSearch" time="1.232"/>
  <testcase classname="testCases.TC_005_AddToCartPageTest" name="test_addToCart" time="4.241"/>
  <testcase classname="testCases.TC_006_EndToEndTest" name="endToendTest" time="45.724"/>
</testsuite> <!-- Test -->
